name: build and test

on:
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs:
  UnitTestService:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Load environment variables from .env.template
        run: |
          if [ -f .env.template ]; then
            echo "Loading environment variables from .env.template"
            while IFS= read -r line || [[ -n "$line" ]]; do
              if [[ "$line" == *=* ]]; then
                echo "$line" >> "$GITHUB_ENV"
              fi
            done < .env.template
          else
            echo ".env.template not found"
            exit 1
          fi

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Move and rename .env file
        run: mv .env.template .env

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew test

  IntegrationTestService:
    runs-on: ubuntu-latest
    needs: UnitTestService
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Move and rename .env file
        run: mv .env.template .env

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test with Gradle
        run: ./gradlew integrationTest

  BuildService:
    runs-on: ubuntu-latest
    needs: IntegrationTestService
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Load environment variables from .env.template
        run: |
          if [ -f .env.template ]; then
            echo "Loading environment variables from .env.template"
            while IFS= read -r line || [[ -n "$line" ]]; do
              if [[ "$line" == *=* ]]; then
                echo "$line" >> "$GITHUB_ENV"
              fi
            done < .env.template
          else
            echo ".env.template not found"
            exit 1
          fi

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Move and rename .env file
        run: mv .env.template .env

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build --stacktrace -x test -x integrationTest